### ISSUE TITLE
pemの最後に空行がある際にpanicする

### ISSUE THREAD

**Issue by alf-ytakada** [heartbeatsjp/check-tls-cert#20]
素晴らしいツールをありがとうございます:bow:
表示も見やすく、めちゃくちゃ便利です！

利用させていただいた際に、panicしましたのでご報告いたします。

https://github.com/heartbeatsjp/check-tls-cert/blob/a3483dc0cb433837020f8fe6a1db1165d211e041/x509util/certificate.go#L32

こちらの `pem.Decode` ですが、ファイルの最後に空行があると `block` がnilとなり、panicしてしまいました。
[pem.Decode](https://pkg.go.dev/encoding/pem#Decode)

補足ですが、
pemの仕様では [こちら](https://wiki.suikawiki.org/n/pem%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB$24080#anchor-13)を参照すると、メッセージの最後には余計なデータは追加できないようです。
その意味で、たまたま手元にあったpemファイルがおかしいと言えると思いますので、
本動作も決してバグであるとは思っておりません。
※opensslは問題なく読み込んでくれるようで、nginxも元気に稼働してくれました

念の為ご報告させていただきます。

**Comment by ttkzw** [comment]
報告ありがとうございます。

この問題を修正したはずのv0.4.3をリリースしましたので、確認いただけると助かります。

**Comment by alf-ytakada** [comment]
ご対応ありがとうございます。
末尾に空行がある場合にも問題なく動作することを確認致しました。
closeさせていただきます:bow:
